# Generated by Django 4.0 on 2022-02-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedmodel',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='model',
            field=models.FileField(default='', null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='threedmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
