# Generated by Django 3.1.7 on 2022-02-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_threedmodel_image_threedmodel_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='threedmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
